version: '3.9'

services:
  db:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=todoapp
      - POSTGRES_DB=todoapp